/***********************************************************************/
/*                                                                     */
/*  FILE        :THERMO_.c                                             */
/*  DATE        :Mon, May 23, 2016                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  
#include "iodefine.h"
#include "lcd_func.h"

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{
	unsigned int tmp_data = 0;
	unsigned int tmp_out;
	
	// 初期設定
	lcd_init();				// LCD初期化
	AD.ADCSR.BYTE = 0x04;	// 単一モード、AN4を使用
	
	// 常に固定の文字をLCDに出力
	lcd_xy(1,1);
	lcd_puts("TMP :   [ﾟC]");
	
	// 変換・出力
	while (1) {
		AD.ADCSR.BIT.ADST = 1;	// A/D変換開始
		
		while(!AD.ADCSR.BIT.ADF);	// A/D変換終了まで待機
		
		tmp_data = AD.ADDRA>>6;	// 10ビット変換データ取得
		tmp_out = 25 + ((tmp_data*4.8828)-750)/10;	// 10ビットデータを温度に変換
		
		lcd_xy(7,1);
		lcd_dataout(tmp_out);
		
		AD.ADCSR.BIT.ADF = 0;	// エンドフラグをクリア
	}

}

#ifdef __cplusplus
void abort(void)
{

}
#endif
