/***********************************************************************/
/*                                                                     */
/*  FILE        :SW01.c                                                */
/*  DATE        :Tue, Apr 19, 2016                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  
#include "iodefine.h"

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{
	// èoóÕÇ…êÿÇËë÷Ç¶
	IO.PCR3 = 0xFF;    // LED 0~7
	IO.PCR2 = 0x01;    // BZ
	
	while(1) {
		// SW1
		if(IO.PDR1.BIT.B4 == 0) {
			IO.PDR3.BIT.B1 = 1;
		} else {
			IO.PDR3.BIT.B1 = 0;
		}
		
		// SW2
		if(IO.PDR1.BIT.B5 == 0) {
			IO.PDR3.BIT.B2 = 1;
		} else {
			IO.PDR3.BIT.B2 = 0;
		}
		
		// SW4
		if(IO.PDR1.BIT.B7 == 0) {
			IO.PDR2.BIT.B0 = 1;
		} else {
			IO.PDR2.BIT.B0 = 0;
		}
	}
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
