/***********************************************************************/
/*                                                                     */
/*  FILE        :E_card_parent_.c                                      */
/*  DATE        :Tue, Jul 26, 2016                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  
#include "iodefine.h"
#include "lcd_func.h"
#include <machine.h>

#define EMP 1 // 皇帝 emperor
#define SLV 1 // 奴隷 slave
#define CMN 2 // 平民 commoner

#define WIN 1
#define LOSE 2
#define DRAW 3

unsigned char RevDt;
char flag;
int button_child, button_parent;

void wait(unsigned int count);
void func_sci(void);
void func_SW(char num_sw);

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{
    int result;             // 対戦の結果を格納
    
    lcd_init();
    IO.PCR1 = 0xFF;         // SW1〜SW4は入力
    IO.PMR1.BYTE = 0xF8;    // SW1〜4を割り込みに使用,TXD出力端子の設定
    IEGR1.BYTE = 0x7F;      // 立ち上がりに割り込み
    IENR1.BYTE = 0x1F;      // スイッチ割込許可
    
    SCI3_2.SCR3.BIT.RE = 0; // 受信禁止
    SCI3_2.SCR3.BIT.TE = 0; // 送信禁止
    SCI3_2.SMR.BYTE = 0x00; // 調歩同期、クロック20MB
    SCI3_2.BRR = 64;
    SCI3_2.TDR = 0x00;      // 送信データ初期化
    SCI3_2.SSR.BIT.OER = 0; // 各種エラーのフラグを0に
    SCI3_2.SSR.BIT.FER = 0;
    SCI3_2.SSR.BIT.PER = 0;
        
    wait(2);
    
    result = DRAW;
    while(result == DRAW) {
        // 子（相手）がカードを決める
        lcd_xy(1,1);
        lcd_puts("Waiting....     ");
        flag = 0;
        SCI3_2.SCR3.BIT.RE = 1;     // 受信割込許可
        SCI3_2.SCR3.BIT.RIE = 1;
        while(flag == 0);           // 受信待ち
        SCI3_2.SCR3.BIT.RE = 0;     // 受信割込禁止
        SCI3_2.SCR3.BIT.RIE = 0;
        
        // 親（自分）がカードを決める
        lcd_xy(1,1);
        lcd_puts("Push the button!");
        lcd_xy(1,2);
        lcd_puts("1:ｺｳﾃｲ 2-4:ﾍｲﾐﾝ ");
        while(flag == 1)    // 自分のカード決定待ち
        
        lcd_xy(1,1);
        lcd_puts("                ");
        lcd_xy(1,2);
        lcd_puts("                ");
        lcd_xy(1,1);
        
        // 勝ち負けの判定
        if(button_child == SLV) {
            if(button_parent == CMN)
                result = WIN;
            else
                result = LOSE;
        }
        else if(button_child == CMN) {
            if(button_parent == EMP)
                result = WIN;
            else
                result = DRAW;
        }
        
        // 結果表示・相手に結果送信
        lcd_xy(1,1);
        switch(result) {
        case WIN:
            lcd_puts("You win!!");
            break;
        case LOSE:
            lcd_puts("You lose...");
            break;
        case DRAW:
            lcd_puts("Draw");
            break;
        }
        
        SCI3_2.SCR3.BIT.TE = 1;    // 送信許可
        SCI3_2.TDR = result;       // 相手に結果を送信
        SCI3_2.SCR3.BIT.TE = 0;    // 送信禁止
        
        wait(1000);
    }

}

// 待機関数
void wait(unsigned int count)
{
    unsigned int i, j;
    
    for(i=0; i<=count; i++) {
        for(j=0; j<=2000; j++) {
        } 
    }
}


void func_sci(void)
{
    if(SCI3_2.SSR.BIT.RDRF == 1) {
        button_child = SCI3_2.RDR;
        
        if(button_child != SLV)
            button_child = CMN;
            
        flag = 1;
    }
    else {
        SCI3_2.SSR.BIT.OER = 0;
        SCI3_2.SSR.BIT.FER = 0;
        SCI3_2.SSR.BIT.PER = 0;
    }
}

void func_SW(char num_sw) {
    if(flag == 1) {
        if (num_sw == 1)
            button_parent = EMP;
        else
            button_parent = CMN;
            
        flag = 2;
    
    
        switch(num_sw) {
        case 1:
            IENR1.BIT.IEN0 = 0;     
            break;
        case 2:
            IENR1.BIT.IEN1 = 0;
            break;
        case 3:
            IENR1.BIT.IEN2 = 0;
            break;
        case 4:
            IENR1.BIT.IEN3 = 0;
            break;
            
        }
    }
    
    IRR1.BIT.IRRI0 = 0;
    IRR1.BIT.IRRI1 = 0;
    IRR1.BIT.IRRI2 = 0;
    IRR1.BIT.IRRI3 = 0;
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
