/***********************************************************************/
/*                                                                     */
/*  FILE        :E_card_parent_.c                                      */
/*  DATE        :Tue, Jul 26, 2016                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  
#include "iodefine.h"
#include "lcd_func.h"
#include <machine.h>


unsigned char RevDt;
char flag;
int button_child, button_parent;

void wait(unsigned int count);
void func_sci(void);
void func_SW(char num_sw);

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{
	lcd_init();
	IO.PCR1 = 0xFF; // SW1～SW4は入力
	IO.PMR1.BYTE = 0xF0; // SW1～4を割り込みに使用
	IEGR1.BYTE = 0x7F;	 // 立ち上がりに割り込み
	IENR1.BYTE = 0x1F;	 // 割込許可
	
	SCI3_2.SCR3.BIT.RE = 0;	// 受信禁止
	SCI3_2.SMR.BYTE = 0x00; // 調歩同期、クロック20MB
	SCI3_2.BRR = 64;
	SCI3_2.SSR.BIT.OER = 0;	// 各種エラーのフラグを0に
	SCI3_2.SSR.BIT.FER = 0;
	SCI3_2.SSR.BIT.PER = 0;
		
	wait(2);
	
	SCI3_2.SCR3.BIT.RE = 1;
	SCI3_2.SCR3.BIT.RIE = 1;
	
	//IO.PDR3.BYTE = 0xAA;
	while(1) {
		// 子（相手）がカードを決める
		lcd_xy(1,1);
		lcd_puts("Waiting...      ");
		flag = 0;
		while(flag == 0);
		
		// 親（自分）がカードを決める
		lcd_xy(1,1);
		lcd_puts("Push the button!");
		lcd_xy(1,2);
		lcd_puts("1:ｺｳﾃｲ 2-4:ﾍｲﾐﾝ ");
		
		flag = 0;
		while(flag == 0)	// 自分のカード決定待ち
		//IENR1.BYTE = 0x10;	// 割込禁止
		
		lcd_xy(1,1);
		lcd_puts("                ");
		lcd_xy(1,2);
		lcd_puts("                ");
		
		lcd_xy(1,1);
		lcd_dataout(button_parent);
		lcd_xy(1,2);
		lcd_dataout(button_child);
		
		while(1);
	}

}

// 待機関数
void wait(unsigned int count)
{
	unsigned int i, j;
	
	for(i=0; i<=count; i++) {
		for(j=0; j<=2000; j++) {
		} 
	}
}


void func_sci(void)
{
	if(SCI3_2.SSR.BIT.RDRF == 1) {
		button_child = SCI3_2.RDR;
		flag = 1;
	}
	else {
		SCI3_2.SSR.BIT.OER = 0;
		SCI3_2.SSR.BIT.FER = 0;
		SCI3_2.SSR.BIT.PER = 0;
	}
}

void func_SW(char num_sw) {
	button_parent = num_sw;
	flag = 1;
	
	switch(num_sw) {
	case 1:
		IRR1.BIT.IRRI0 = 0;
		break;
	case 2:
		IRR1.BIT.IRRI1 = 0;
		break;
	case 3:
		IRR1.BIT.IRRI2 = 0;
		break;
	case 4:
		IRR1.BIT.IRRI3 = 0;
		break;
	}
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
