/***********************************************************************/
/*                                                                     */
/*  FILE        :LED03.c                                               */
/*  DATE        :Tue, Apr 19, 2016                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  
#include "iodefine.h"

void wait(unsigned int count)
{
	unsigned int i, j;
	
	for(i=0; i<=count; i++) {
		for(j=0; j<=20000; j++) {
		} 
	}
}

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{
	int led_out = 0x01;    // LEDの出力に使う
	
	// 出力に切り替え
	IO.PCR3 = 0xFF;    
	
	while(1) {
		IO.PDR3.BYTE = led_out;
		wait(100);
		
		led_out = led_out << 1;    // 左にビットシフト
		if(led_out > 0xFF)
			led_out = 0x01;        // 0x100になったら01に戻す
	}
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
