/***********************************************************************/
/*                                                                     */
/*  FILE        :TZ02.c                                                */
/*  DATE        :Tue, May 31, 2016                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  
#include "iodefine.h"
#include "machine.h"

#define CW  1 // 時計回り（C出力）
#define CCW 0 // 反時計回り（D出力）
#define PERIOD 10 // パルス周期[ms]

char rotate_dir = CW; // 現在の回転方向（デフォは時計回り）

// 関数プロトタイプ
void SW1_OFF(void);
void SW2_SwitchRotateDir(void);
void SW34_ChangeRotateSpeed(char innum);
void Motor_ON(void);

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

	
void main(void)
{
	set_imask_ccr(1);
	// 割り込み設定
	IO.PMR1.BYTE = 0xF0; // SW1,3
	IEGR1.BYTE = 0x7F;	 // 立ち上がり
	IENR1.BYTE = 0x1F;	 // 割込許可
	
	// タイマ設定
	TZ0.TCR.BYTE = 0x23; 
	TZ0.POCR.BYTE = 0xF8;
	TZ.TPMR.BYTE = 0x8E;
	TZ.TOCR.BYTE = 0x0c;
	TZ0.GRA = PERIOD * 2500;
	TZ0.GRC = 0;
	TZ0.GRD = 0;
	
	set_imask_ccr(0);
	
	while(1);

}

void SW1_OFF(void)
{
	TZ.TOER.BIT.EC0 = 1; // 両方向とも出力禁止
	TZ.TOER.BIT.ED0 = 1;
	
	TZ0.GRC = 0; // Duty比：0
	TZ0.GRD = 0;
	
	TZ.TSTR.BIT.STR0 = 0; // カウント動作停止
	TZ.TSTR.BIT.STR1 = 0;
	
	IRR1.BIT.IRRI0 = 0; // 割込フラグクリア	
}

void SW2_SwitchRotateDir(void)
{
	if(rotate_dir == CW) {
		rotate_dir = CCW;
	}
	else {
		rotate_dir = CW;
	}	
	
	IRR1.BIT.IRRI1 = 0;
}

void SW34_ChangeRotateSpeed(char innum)
{
	unsigned int rotate_speed = TZ0.GRA; // ベース（100%出力）
	
	// 回転速度の決定
	if(innum == 3) {
		rotate_speed *= 0.25; // 25%
	}
	else {
		rotate_speed *= 0.75; // 75%
	}
	
	// 出力ポート指定		
	if(rotate_dir == CW) {
		TZ0.GRC = rotate_speed;
	}
	else {
		TZ0.GRD = rotate_speed;
	}
	
	Motor_ON();
	
	IRR1.BIT.IRRI2 = 0;
	IRR1.BIT.IRRI3 = 0;
}

void Motor_ON(void)
{
	// モータを回す
	if(rotate_dir == CW) {
		TZ0.TCNT = 0;
		TZ.TOER.BIT.EC0 = 0;
		TZ.TSTR.BIT.STR0 = 1;
	}
	else {
		TZ1.TCNT = 0;
		TZ.TOER.BIT.ED0 = 0;
		TZ.TSTR.BIT.STR0 = 1;
	}
}		

#ifdef __cplusplus
void abort(void)
{

}
#endif
