/***********************************************************************/
/*                                                                     */
/*  FILE        :AD02.c                                                */
/*  DATE        :Tue, May 10, 2016                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  
#include "iodefine.h"
#include "lcd_func.h"

#define PERIOD 10 // パルス周期[ms]

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{
	unsigned int vr1_data = 0, vr2_data = 0;
	unsigned char percent[3];
	int i;
	
	AD.ADCSR.BYTE = 0x16; // スキャンモード、AN4からAN6
	
	lcd_init();	// LCD初期化
	lcd_xy(1,1);
	lcd_puts("VR1:   [%]");
	lcd_xy(1,2);
	lcd_puts("VR2:   [%]");
	
	AD.ADCSR.BIT.ADST = 1;	// 変換スタート
	while (1) {
		
		while (!AD.ADCSR.BIT.ADF);	// 変換終了まで待機
		
		vr1_data = AD.ADDRB >> 6;	// 10bitデータ取得
		vr2_data = AD.ADDRC >> 6;
		
		// 10bitデータを%に変換
		percent[1] = (unsigned char)(((double)vr1_data*0.0977) + 0.5);	// 0.0977 ≒　100/1023
		percent[2] = (unsigned char)(((double)vr2_data*0.0977) + 0.5);
		
		// 出力
		for (i=1; i<=2; i++) {
			lcd_xy(5,i);
			if(percent[i] == 100) {
				lcd_xy(5,i);
			}
			else if(percent[i] >= 10) {
				lcd_puts(" ");
				lcd_xy(6,i);
			}
			else {
				lcd_puts("  ");
				lcd_xy(7,i);
			}
			
			lcd_dataout(percent[i]);
		}
		
		AD.ADCSR.BIT.ADF = 0;	// エンドフラグをクリア

	}

}

#ifdef __cplusplus
void abort(void)
{

}
#endif
