/***********************************************************************/
/*                                                                     */
/*  FILE        :E_card_child.c                                        */
/*  DATE        :Tue, Jul 12, 2016                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
       
int button = 0;	//選択されたボタンの番号
int flag = 0;	//受信の有無の変数
int result;		//送られてくる結果
     
#include "iodefine.h"
#include "lcd_func.h"
#include <machine.h>

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void wait(unsigned int count)
{
	 unsigned int i, j; 
	 
	 for(i=0; i<=count; i++)
	 {
		for(j=0; j<=50000; j++)
		{
			  ;
		}
	 }
}

void SW1_EorS()
{
	button = 1;	//ボタン1が押された時
	IRR1.BIT.IRRI0 = 0;
}

void SW2()
{
		lcd_xy(1,1);
		lcd_puts("tinko");
	button = 2;	//ボタン2が押された時
	IRR1.BIT.IRRI1 = 0;
}

void SW3()
{
	button = 3;	//ボタン3が押された時
	IRR1.BIT.IRRI2 = 0;
}

void SW4()
{
	button = 4;	//ボタン4が押された時
	IRR1.BIT.IRRI3 = 0;
}

void func_sci()
{
	if(SCI3_2.SSR.BIT.RDRF == 1)
	{
		result = SCI3_2.RDR;
		flag = 1;
	}
	
	else
	{
		SCI3_2.SSR.BIT.OER = 0;
		SCI3_2.SSR.BIT.FER = 0;
		SCI3_2.SSR.BIT.PER = 0;
	}
}

void main(void)
{
	lcd_init();	//LCDの初期化
	
	IO.PCR1 = 0xFF;	//ポート1
	IO.PMR1.BYTE = 0xF8;
	IEGR1.BYTE = 0x7F;
	IENR1.BYTE = 0x1F;
	IRR1.BYTE = 0x30;
	
	SCI3_2.SCR3.BIT.TE = 0;
	
	SCI3_2.SMR.BYTE = 0x00;
	SCI3_2.BRR = 64;
	SCI3_2.TDR = 0x00;
	
	wait(2);
	
	SCI3_2.SCR3.BIT.TE = 1;
	SCI3_2.SCR3.BIT.RE = 1;
	SCI3_2.SCR3.BIT.RIE = 1;
	
	result = 3;
	
	IENR1.BYTE = 0x1F;	
	
	while(result == 3)
	{				
		lcd_xy(1,1);
		lcd_puts("Push the button!");
		lcd_xy(1,2);
		lcd_puts("1:ﾄﾞﾚｲ 2-4:ﾍｲﾐﾝ");
		
		button = 0;
		
		while(1)
		{		
			if(button != 0 &&
				SCI3_2.SSR.BIT.TDRE == 1)
			{
				switch(button)
				{
					case 1:SCI3_2.TDR = 1;	//ボタン1が押された時に1(奴隷)を送る
							IENR1.BIT.IEN0 = 0;
							break;
					case 2:SCI3_2.TDR = 2;	//ボタン2が押された時に2(平民)を送る
							IENR1.BIT.IEN1 = 0;
							break;
					case 3:SCI3_2.TDR = 3;	//ボタン3が押された時に2(平民)を送る
							IENR1.BIT.IEN2 = 0;
							break;
					case 4:SCI3_2.TDR = 4;	//ボタン4が押された時に2(平民)を送る
							IENR1.BIT.IEN3 = 0;
							break;
				}
				button = 0;
				break;
			}
		}
		
		lcd_xy(1,1);
		lcd_puts("Waiting...      ");
		lcd_xy(1,2);
		lcd_puts("                ");
		
		flag = 0;
		while(flag == 0);	//データを受信するまでWaiting
			
		switch(result)
		{
			case 1:	lcd_xy(1,1);
					lcd_puts("You Lose...    ");
					break;
			case 2:	lcd_xy(1,1);
					lcd_puts("You Win!!       ");
					break;	
			case 3:	lcd_xy(1,1);
					lcd_puts("Draw!           ");	
					break;		
		}	
		wait(20);	
	}			
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
