/***********************************************************************/
/*                                                                     */
/*  FILE        :MOTOR.c                                               */
/*  DATE        :Tue, Jun 21, 2016                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  
#include "iodefine.h"
#include "lcd_func.h"
#include <machine.h>

char flag_motor = 1;	// 1:モータON、-1:モータOFF

void SW1_MOTOR(void);
	
void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{
	unsigned int vr1_data = 0, vr1_percent = 0;
	int i;
	
	AD.ADCSR.BYTE = 0x16; // スキャンモード、AN4からAN6
	
	lcd_init();	// LCD初期化
	lcd_xy(1,1);
	lcd_puts(" VR1  :    [%]");
	lcd_xy(1,2);
	lcd_puts("MOTOR :");

	set_imask_ccr(1);
	
	// 割り込み設定
	IO.PMR1.BYTE = 0x10; // SW1
	IEGR1.BYTE = 0x71;	 // 立ち上がり
	IENR1.BYTE = 0x11;	 // 割込許可
	// タイマ設定
	TZ0.TCR.BYTE = 0x23;		// プリスケーラ等設定
	TZ0.POCR.BYTE = 0xF8;		// ローアクティブ
	TZ.TPMR.BYTE = 0x8E;		// モータ出力端子をPWM制御
	TZ.TOCR.BYTE = 0x0C;		// 初期出力は1
	TZ0.GRA = 25000;	// 周期設定
	TZ0.GRC = 0;
	TZ0.GRD = 0;		// 使わない
	
	set_imask_ccr(0);
	
	TZ0.TCNT = 0;				// カウンタクリア
	TZ.TOER.BIT.EC0 = 0;		// 端子のPWM出力を許可
	TZ.TSTR.BIT.STR0 = 1;		// カウントスタート
	
	AD.ADCSR.BIT.ADST = 1;	// 変換スタート
	while (1) {
		
		while (!AD.ADCSR.BIT.ADF);	// 変換終了まで待機
		
		vr1_data = AD.ADDRB >> 6;	// 10bitデータ取得
		
		// 10bitデータを%に変換
		vr1_percent = (unsigned char)(((double)vr1_data*0.0977) + 0.5);	// 0.0977 ≒　100/1023
		
		// 出力
		if(vr1_percent == 100) {
			lcd_xy(9,1);
		}
		else if(vr1_percent >= 10) {
			lcd_xy(9,1);
			lcd_puts(" ");
			lcd_xy(10,1);
		}
		else {
			lcd_xy(9,1);
			lcd_puts("  ");
			lcd_xy(11,1);
		}
			
		lcd_dataout(vr1_percent);
		
		AD.ADCSR.BIT.ADF = 0;	// エンドフラグをクリア
		
		if(flag_motor == 1) {
			lcd_xy(9,2);
			lcd_puts("ON ");
			TZ0.GRC = 24999 * ((double)vr1_percent/100);
		}
		else {
			TZ0.GRC = 0;
			lcd_xy(9,2);
			lcd_puts("OFF");
		}

	}

}

void SW1_MOTOR(void)
{
	flag_motor *= -1;
	
	IRR1.BIT.IRRI0 = 0;	// フラグクリア
}


#ifdef __cplusplus
void abort(void)
{

}
#endif
