/***********************************************************************/
/*                                                                     */
/*  FILE        :ENC01.c                                               */
/*  DATE        :Tue, Jun 14, 2016                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  
#include "iodefine.h"
#include "machine.h"
#include "lcd_func.h"

int cont = 0;

void WKP_func(void);
void printLCD(void);

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{
	lcd_init();
	
	IO.PCR5 = 0xFC;
	IO.PUCR5.BYTE = 0x03;
	
	set_imask_ccr(1);
	
	IO.PMR5.BYTE = 0x01;
	IEGR2.BYTE = 0x01;
	IENR1.BIT.IENWP = 1;
	IWPR.BYTE = 0x00;

	lcd_xy(1,1);
	lcd_puts("PULSE :");
	lcd_xy(1,2);
	lcd_puts(" DEG  :");
	
	set_imask_ccr(0);
	
	printLCD();
		
	while(1) {
		printLCD();
	}
}

void WKP_func(void)
{
	if(IO.PDR5.BIT.B1 == 1) {
		cont++;
	}
	else {
		cont--;
	}

	IWPR.BIT.IWPF0 = 0;
}	

void printLCD()
{
	lcd_xy(9,1);
	lcd_puts("        ");
	lcd_xy(9,2);
	lcd_puts("        ");
	
	if(cont > 0) {
		lcd_xy(9,1);
		lcd_puts("+");
		lcd_dataout(cont);
		
		lcd_xy(9,2);
		lcd_puts("+");
		lcd_dataout((unsigned int)((double)cont * 3.3333)); // 3.3333 = 360/108
		
		return;
	}
	if(cont < 0) {
		lcd_xy(9,1);
		lcd_puts("-");
		lcd_dataout(cont*(-1));
		
		lcd_xy(9,2);
		lcd_puts("-");
		lcd_dataout((unsigned int)((double)cont * -3.3333));
		
		return;
	}
	if(cont == 0) {
		lcd_xy(10,1);
		lcd_puts("0");
		
		lcd_xy(10,2);
		lcd_puts("0");
		
		return;
	}	
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
