/***********************************************************************/
/*                                                                     */
/*  FILE        :7SEG01.c                                              */
/*  DATE        :Tue, Apr 26, 2016                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
           
#include "iodefine.h"
#include "lcd_func.h"


void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{
	char count = 0x00;
	int flag_SW1 = 0, flag_SW2 = 0, flag_SW4 = 0;
		
	IO.PCR5 = 0x0F;
	
	while(1) {
		IO.PDR5.BYTE = count;
		
		if(IO.PDR1.BIT.B4 == 0 && !flag_SW1) {
			count++;
			flag_SW1 = 1;
			
			if(count >= 10) {
				count = 0;
			}
		} 
		else if(IO.PDR1.BIT.B5 == 0 && !flag_SW2) {
			count--;
			flag_SW2 = 1;
			
			if(count < 0) {
				count = 9;
			}
		}
		else if(IO.PDR1.BIT.B7 == 0 && !flag_SW4) {
			count = 0;
		} 
		
		if(IO.PDR1.BIT.B4) {
			flag_SW1 = 0;
		}
		if(IO.PDR1.BIT.B5) {
			flag_SW2 = 0;
		}
		if(IO.PDR1.BIT.B7) {
			flag_SW4 = 0;
		}
	}

}

#ifdef __cplusplus
void abort(void)
{

}
#endif
