/***********************************************************************/
/*                                                                     */
/*  FILE        :SW03.c                                                */
/*  DATE        :Tue, May 17, 2016                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  
#include "iodefine.h"
#include "machine.h"

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

//　引数のビットを反転
char turn(char innum)
{
	return (innum == 1) ? 0 : 1;
}

// 待機 引数（およそミリ秒）だけ待機
void wait(unsigned int count)
{
	unsigned int i, j;
	
	for(i=0; i<=count; i++) {
		for(j=0; j<=2000; j++) {
		} 
	}
}

void SW1(void)
{
	IO.PDR3.BIT.B1 = turn(IO.PDR3.BIT.B1);
	IRR1.BIT.IRRI0 = 0;
}

void SW2(void)
{
	IO.PDR3.BIT.B2 = turn(IO.PDR3.BIT.B2);
	IRR1.BIT.IRRI1 = 0;
}

void SW3(void)
{
	IO.PDR3.BIT.B3 = turn(IO.PDR3.BIT.B3);
	IRR1.BIT.IRRI2 = 0;
}

void SW4(void)
{
	IO.PDR3.BIT.B4 = turn(IO.PDR3.BIT.B4);
	IRR1.BIT.IRRI3 = 0;
}

void main(void)
{
	int i = 1;
	set_imask_ccr(1);
	
	IO.PCR1 = 0x00; // SW1～SW4は入力
	IO.PCR3 = 0xFF; // LED1～4,7を出力に
	
	IO.PMR1.BYTE = 0xF0; // SW1～4を割り込みに使用
	IEGR1.BYTE = 0x7F;	 // 立ち上がりに割り込み
	IENR1.BYTE = 0x1F;	 // 割り込み許可
	
	set_imask_ccr(0);
	
	while(1) {
		IO.PDR3.BIT.B7 = turn(IO.PDR3.BIT.B7);	// LED7のON/OFF反転
		wait(1000);	// 待機
	}

}

#ifdef __cplusplus
void abort(void)
{

}
#endif
